### ISSUE TITLE
IEEE format request

### ISSUE THREAD

**Issue by Admin-OF-Admin** [enric1994/bibtexonline#10]
Hello! Thanks for sharing this project. It's very convenient but I want to use this in IEEE format. Can u add this format as a choice? Thank  you so much!

**Comment by enric1994** [comment]
Got it! I'm a bit swamped right now but I'll probably get to this sometime next week. I'll keep you in the loop.

**Comment by enric1994** [comment]
Fixed! Thanks for your patience https://github.com/enric1994/bibtexonline/pull/11
