### ISSUE TITLE
Missing punctuation in APA conversion

### ISSUE THREAD

**Issue by yyxy-dev** [enric1994/bibtexonline#3]
When citing an article, the resulting APA citation lacks a period and a space between the title and the journal. Here's an example:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/77182551/109606150-db4b9900-7aeb-11eb-9128-7e38c13e07ac.png">
With the input:
`@article{10.2307/26229225,
 ISSN = {11763647, 14364522},
 URL = {http://www.jstor.org/stable/26229225},
 author = {Yiling Hu and Bian Wu and Xiaoqing Gu},
 journal = {Journal of Educational Technology & Society},
 number = {4},
 pages = {300--311},
 publisher = {International Forum of Educational Technology & Society},
 title = {An Eye Tracking Study of High- and Low-Performing Students in Solving Interactive and Analytical Problems},
 volume = {20},
 year = {2017}
}
`

Here is another example:
<img width="935" alt="image" src="https://user-images.githubusercontent.com/77182551/109606433-4a28f200-7aec-11eb-861a-1c5e660ce0da.png">
With the input:
`@article{10.2307/26943245,
 ISSN = {09598138, 17561833},
 URL = {https://www.jstor.org/stable/26943245},
 author = {Derek K Tracy and David M Wood and David Baumeister},
 journal = {BMJ: British Medical Journal},
 number = {},
 publisher = {BMJ},
 title = {Novel psychoactive substances: identifying and managing acute and chronic harmful use},
 volume = {356},
 year = {2017}
}
`

**Comment by enric1994** [comment]
Fixed in #4 by @danish17 
Huge thanks to all of you for reporting/fixing errors
